name: Deploy backend to EC2

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Generate SSH key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > ~/secret.pem
          chmod 600 ~/secret.pem
          ssh -o StrictHostKeyChecking=no -i "~/secret.pem" ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '   
          cd /home/ubuntu/south_stays 
          pm2 stop all
          git fetch origin master
          git reset --hard origin master
          cd client 
          npm install && npm run build
          cd ../api && npm install 
          pm2 start index.js
          exit
          '
          
